---
EnableDefaultLinters: true

linters:
  Rubocop:
    enabled: true
    # プロジェクトの .rubocop.yml を読み込んで連動させる設定
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/LineLength:
        Enabled: false
      Layout/InitialIndentation:
        Enabled: false
      Layout/TrailingWhitespace:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/SpaceInsideBlockBraces:
        Enabled: false
      Layout/IndentationConsistency:
        Enabled: false
